version: "3.1"

services:
  
  opendlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opendlp-test
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./OpenDLP-2:/var/www/OpenDLP
      - ./sites-available/:/etc/apache2/sites-available/
      - ./sites-enabled/:/etc/apache2/sites-enabled
      - ./ssl/:/etc/apache2/ssl/
    command: ["apache2ctl start", "tail -F anything"]
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    ports:
        - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
        - ./OpenDLP-2/web/etc/default_regexes:/data/default_regexes
    environment:
        MYSQL_ROOT_USER: OpenDLP
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_DATABASE: OpenDLP
        MYSQL_USER: OpenDLP
        MYSQL_PASSWORD: '684239715'
  